### ISSUE TITLE
Exeption after Installing 1.0.5 via Composer

### ISSUE THREAD

**Issue by sven-codeculture** [coingate/magento2-plugin#3]
Hi Coingate Team,

i was Installing the Plugin via composer on the Actual version.
After activating the Payment Method our Magento 2.1.4 is only showing the following Exception:

```
Fatal error: Uncaught Error: Call to undefined method CoinGate\Merchant::initialize() in /www/vendor/coingate/magento2-plugin/Model/Payment.php:97 Stack trace: #0 /www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): CoinGate\Merchant\Model\Payment->__construct(Object(Magento\Framework\Model\Context), Object(Magento\Framework\Registry), Object(Magento\Framework\Api\ExtensionAttributesFactory), Object(Magento\Framework\Api\AttributeValueFactory), Object(Magento\Payment\Helper\Data), Object(Magento\Framework\App\Config), Object(Magento\Payment\Model\Method\Logger), Object(CoinGate\Merchant), Object(Magento\Framework\Url), Object(Magento\Store\Model\StoreManager), NULL, NULL, Array) #1 /www/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('CoinGate\\Mercha...', Array) #2 /www/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Compiled->create('CoinGate\\Mercha...', Ar in /www/vendor/coingate/magento2-plugin/Model/Payment.php on line 97
```

I have installed the version 1.0.4 for now and it seems to work for now. 
I still hope that you can fix this problem since we normally prefer to be on the actual version when installing something :).

Greetings Sven

**Comment by rytisbitcoin** [comment]
Problem fixed in plugin version 1.0.6. Thank you for reporting.
